### ISSUE TITLE
Crash when trying to take health in creative

### ISSUE THREAD

**Issue by jackrtades** [TheidenHD/Psi#3]
# Version Information
Forge version: 47.3.11
Psi version: 1.20-103
<script src="https://gist.github.com/jackrtades/a9dc05aa09f5f00c5559ae55606cc6f8.js"></script>

# Further Information
Steps to reproduce:
1. I cast a spell that took all of my energy and when it ticked down to take health it crashed.
The spell
{modsRequired:[{modName:"psi",modVersion:"2.0.0"}],spellList:[{data:{key:"psi:trick_smite",params:{_position:2}},x:1,y:4},{data:{key:"psi:operator_entity_position",params:{_target:4}},x:1,y:5},{data:{constantValue:"32",key:"psi:constant_number"},x:2,y:3},{data:{key:"psi:selector_nearby_enemies",params:{_position:4,_radius:1}},x:2,y:4},{data:{key:"psi:operator_random_entity",params:{_target:1}},x:2,y:5},{data:{key:"psi:error_suppressor"},x:3,y:3},{data:{key:"psi:operator_entity_position",params:{_target:2}},x:3,y:4},{data:{key:"psi:selector_focal_point"},x:3,y:5}],spellName:"Smite (Ajustable)",uuidLeast:-6327469632632222565L,uuidMost:7394119008134316247L,validSpell:1b}

What I expected to happen: spell stops

What happened instead: game crashes

**Comment by TheidenHD** [comment]
This should be fixed with Alpha 6. If it's still there send a crash report.

**Comment by Syntax3rr** [comment]
Still an issue:

```
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "net.minecraftforge.registries.ForgeRegistry.getHolder(net.minecraft.resources.ResourceKey)" because the return value of "net.minecraftforge.registries.RegistryManager.getRegistry(net.minecraft.resources.ResourceKey)" is null
	at vazkii.psi.common.core.handler.PlayerDataHandler$PlayerData.deductPsi(PlayerDataHandler.java:693) ~[Psi-1.20-103.jar%23159!/:1.20-103] {re:classloading}
```


[crash-2025-01-29_13.04.36-server.txt](https://github.com/user-attachments/files/18592172/crash-2025-01-29_13.04.36-server.txt)

**Comment by TheidenHD** [comment]
Can you please check if it is fixed?
https://github.com/TheidenHD/Psi/releases/tag/1.20-Alpha-7

**Comment by Syntax3rr** [comment]
Fixed! Thanks for the hard work!
